trigger: none

parameters:
- name: branch
  type: string
  displayName: "Select Branch of the repo"
  default: main
  values:
  - main
  - master
  - custom

variables:
  - template: variables/variables.yml

stages:

    - stage: kvsto
      displayName: "Deploy KV and Storage account"
      jobs:
        - template: stages/sta-kvsto.yml
        
    - stage: passcript
      displayName: "Generate a Random Password and Upload Setup Script"
      jobs:
        - template: stages/sta-passcript.yml

    - stage: depvm
      displayName: "Deploy the VM and run Setup Script"
      jobs:
        - template: stages/sta-depvm.yml
    
    - stage: winrmsetup
      displayName: "Install Office through WINRM"
      jobs:
        - template: stages/sta-winrmsetup.yml
    
    - stage: advm
      displayName: "Setup AD Login in the VM"
      jobs:
        - template: stages/sta-advm.yml
