jobs:
    - job: infraartifact
      displayName: "Build Azure IBC Artifact"
      pool:
          vmImage: ubuntu-latest
      steps:
          - template: jobs/azure-artifact.yml

    - job: kvstodeploy
      displayName: "Install Extension in VM and Setup AD Roles"
      pool:
          vmImage: ubuntu-latest
      dependsOn: infraartifact
      steps:
          - template: jobs/azure-adlogin.yml