jobs:
    - job: dotnetbuild
      displayName: "Build DOTNET project"
      pool:
          vmImage: ubuntu-latest
      steps:
          - template: ../jobs/dotnet-build.yml

    - job: nodebuild
      displayName: "Build NODE project"
      pool:
          vmImage: ubuntu-latest
      steps:
          - template: ../jobs/node-build.yml

    - job: nodedeploy
      displayName: "Deploy NODE project"
      pool:
          vmImage: ubuntu-latest
      dependsOn:
          - nodebuild
      steps:
          - template: ../jobs/node-deploy.yml

    - job: dotnetdeploy
      displayName: "Deploy DOTNET project"
      pool:
          vmImage: ubuntu-latest
      dependsOn:
          - dotnetbuild
      steps:
          - template: ../jobs/dotnet-deploy.yml
