jobs:
    - job: setpass
      displayName: "Create a New Password and store it in KV"
      pool:
          vmImage: ubuntu-latest
      steps:
          - template: jobs/azure-setpass.yml

    - job: uploadscript
      displayName: "Upload Scripts to StorageAccount BLOB"
      pool:
          vmImage: ubuntu-latest
      steps:
          - template: jobs/azure-uploadscript.yml

